name: Build KPM

on:
  push:
    paths:
      - 'kpms/**'
      - '.github/workflows/**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26d

      - name: Build Performance KPM
        run: |
          cd kpms/performance-kpm
          # Use Android NDK Clang to compile. This guarantees compatible ELFs and Relocation Types.
          export TARGET_COMPILE="${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-"
          make CC="${TARGET_COMPILE}34-clang" LD="${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld"
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: performance-kpm
          path: kpms/performance-kpm/*.kpm